
application: amayadori-opt
version: v4
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico
- url: /about
  static_files: public/about.html
  upload: public/about.html
- url: /image/.*
  script: image_handler.py
- url: /task/.*
  script: task_handler.py
- url: /.*
  script: main_handler.py
