
application: amayadori-opt
version: v2
runtime: python
api_version: 1

handlers:
#- url: /
#  script: app.py
#- url: /(.*\.html)
#  static_files: public/\1
#  upload: public/(.*\.html)

- url: /image/.*
  script: image_handler.py
- url: /task/.*
  script: task_handler.py
- url: /.*
  script: main_handler.py
