
application: amayadori-opt
version: test
runtime: python
api_version: 1

handlers:
- url: /
  script: app.py
- url: /images/[0-9]+/observed.png
  script: images_observed.py
- url: /images/[0-9]+/predictive/[0-9].png
  script: images_predictive.py
